### ISSUE TITLE
AWSAccessKeyId is visible in a link

### ISSUE THREAD

**Issue by drorata** [stevearc/pypicloud-docker#28]
I'm trying to host a python package on S3 using pypicloud (as per the this answer https://stackoverflow.com/a/56369441/671013). I managed to get it running rather quickly using the docker version from this repo. But, in the UI when I hover over the newly uploaded package, then my AWSAccessKeyId credentials (that I provided as env-vars to the container) is rendered in the link! That feel like a serious security issue. Am I missing something?

**Comment by stevearc** [comment]
The Access Key ID is safe to expose to the public
https://stackoverflow.com/questions/30609663/aws-s3-the-security-of-a-signed-url-as-a-hyperlink
