### ISSUE TITLE
Redis?

### ISSUE THREAD

**Issue by kevart** [stevearc/pypicloud-docker#4]
redis is installed ([here](https://github.com/stevearc/pypicloud-docker/blob/master/Dockerfile#L14)) but there is no section in the config file neither there is a startup script (in /etc/my_init.d) for it.

**Comment by stevearc** [comment]
Redis is installed so that the python redis client works, you're not supposed to run redis within the same container. Docker best practices are to [run one service per container](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run-only-one-process-per-container).
